version: '3.7'
    
services:
  yrs-backend:
    build: .
    image: yrs-backend
    ports: 
      - 5000:5000
    environment:
      - FLASK_APP=yrs
      - FLASK_ENV
      - SENTRY_DSN
      - ${SENTRY_ENVIRONMENT:-development}
      - SENTRY_RELEASE
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
    networks:
      - yearn-exporter_yearn-exporter
    restart: unless-stopped

networks:
  yearn-exporter_yearn-exporter:
    external: true
